---
title: "Spatial Analysis"
author: "Halina Malinowski"
date: "4/10/2022"
output:
  html_document: default
  pdf_document: default
---

###Set up! 

```{r setup, echo = FALSE}
#Check working directory
getwd()

#Load packages 
library(tidyverse)
library(sf)
library(leaflet)
library(mapview)
library(lubridate)
library(RColorBrewer)
library(raster)
library(webshot)


#Set theme
mytheme <- theme_light(base_size = 12) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "right")
theme_set

```

```{r creating map of Africa}

Africa <- st_read('/Users/Dell Laptop/Documents/GitHub/GoldenGriffithsKnierMalinowski_ENV872_EDA_FinalProject/Data/Spatial Files/Africa/afr_g2014_2013_0.shp')

#Determine coordinate reference system & explore columns
st_crs(Africa)#WGS 84
colnames(Africa)

#Map of Africa
mapView(Africa,zcol = "ADM0_NAME")

```

```{r Map of Gabon}
#Making Gabon sf
Gabon <- Africa %>%
  filter(ADM0_NAME == 'Gabon')

#Maping Gabon
mapview(Africa, col.regions = "mediumpurple3")+ 
  mapview(Gabon, col.regions = "springgreen")

ggplot() +
  geom_sf(data = Africa, aes(fill = "A"), color= 'black', alpha = 0.5, show.legend = "polygon", inherit.aes = F) + 
  geom_sf(data = Gabon,aes(fill = "B"), color='darkgreen', alpha = 0.85, show.legend = "polygon", inherit.aes = F)+
  scale_fill_manual(values = c("A" = "mediumpurple3", "B" = "palegreen3"),
                    labels = c("Continental Africa", "Gabon"),
                    name = "Legend")+
  ggtitle(label = "Map of Africa with Gabon Indicated")

```

```{r Detailed Map of Gabon with parks}
#Parks sf
Parks <- st_read('/Users/Dell Laptop/Documents/GitHub/GoldenGriffithsKnierMalinowski_ENV872_EDA_FinalProject/Data/Spatial Files/Gabon/National Parks/NP_PresRes.shp')

st_crs(Parks) #Gtm_Gabon
colnames(Parks)

#change crs to WGS 84
National_Parks <- st_transform(Parks, "+proj=longlat +datum=WGS84")
st_crs(National_Parks)

#Getting Ivindo National Park by itself
Ivindo_NP <- National_Parks %>%
  filter(NOM == "IVINDO")

mapview(Gabon, col.regions = "palegreen1")+
  mapview(National_Parks, col.region = "palegreen3")+
  mapview(Ivindo_NP, col.region = "darkgreen", lwd = 1.5, color = "black")
 
#Map with ggplot
ggplot() +
  geom_sf(data = Gabon, aes(fill = "A"), color='darkgreen', size = 0.6, alpha = 0.6, show.legend = "polygon", inherit.aes = F) +
  geom_sf(data = National_Parks, aes(fill = "B"), color = 'palegreen3', alpha = 0.7, show.legend = "polygon", inherit.aes = F)+
  geom_sf(data = Ivindo_NP, aes(fill = "C"), color='black', size=0.5, alpha = 0.7, show.legend = "polygon", inherit.aes = F) + 
    scale_fill_manual(values = c("A" = "palegreen1", "B" = "palegreen3", "C" = "darkgreen"),
                    labels = c("Gabon", "National Parks", "Ivindo National Park"), name = "Legend")+
  ggtitle(label = "Gabon's National Parks")

``` 



```{r Map of Ivindo with plots}

#Rivers sf 
Rivers <- st_read('/Users/Dell Laptop/Documents/GitHub/GoldenGriffithsKnierMalinowski_ENV872_EDA_FinalProject/Data/Spatial Files/Gabon/Stream/GAB_hydro_lineaire_principal_2013/GAB_hydro_lineaire_principal_2013.shp')
st_crs(Rivers)

#Roads sf
Roads <- st_read('/Users/Dell Laptop/Documents/GitHub/GoldenGriffithsKnierMalinowski_ENV872_EDA_FinalProject/Data/Spatial Files/Gabon/Roads/GAB_major_roads_2013.shp')
st_crs(Roads)
  
#Makokou village
Makokou <- read_csv('/Users/Dell Laptop/Documents/GitHub/GoldenGriffithsKnierMalinowski_ENV872_EDA_FinalProject/Data/Spatial Files/Gabon/Makokou_Coordinates.csv')%>%
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = "+proj=longlat +datum=WGS84")
st_crs(Makokou)
Makokou_WGS84 <- st_transform(Makokou, "+proj=longlat +datum=WGS84")


#Plots sf
Plots <- st_read('/Users/Dell Laptop/Documents/GitHub/GoldenGriffithsKnierMalinowski_ENV872_EDA_FinalProject/Data/Spatial Files/Gabon/Plots/Plots with species/plots_with_species.shp')

#CRS
st_crs(Plots) #WGS 84
colnames(Plots)

#Map Gabon with Parks and Plots
mapviewPalette(name = "mapviewVectorColors")

mapview(Ivindo_NP, col.region = "palegreen2", lwd = 1, color = "black", alpha.regions = 0.5)+
  mapview(Plots, zcol = "Plot_Name", col.region = c("orangered","magenta","red","gold","orange","yellow"), cex = 4, alpha.regions = 0.70)+
  mapview(Makokou, col.region = "black", cex = 4, alpha.regions = 0.95)

ggplot() +
  geom_sf(data = Ivindo_NP, aes(fill = "A"), color='black', size = 0.5, alpha = 0.65, show.legend = "polygon", inherit.aes = F) +
  geom_sf(data = Plots, aes(color = "B"), size = 1.5, alpha = 0.5, show.legend = "point", inherit.aes = F)+
  geom_sf(data = Makokou, aes(color = "C"), size= 2, alpha = 0.7, show.legend = "point", inherit.aes = F) + 
    scale_fill_manual(values = c("A" = "palegreen2"),
                    labels = c("Ivindo National Park"), name = "Legend",
guide = guide_legend(override.aes = list(shape = NA)))+
  scale_color_manual(values = c("B" = "red", "C" = "black"), 
                     labels = c("Plots", "Makokou"),
                     guide = guide_legend(override.aes = list(linetype = c("blank"))))+
  ggtitle(label = "Forest Plots along a Defaunation Gradient", subtitle = "Ivindo National Park, Gabon")

```

